
services:
  database:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: saas
    ports:
      - "${DB_PORT}:5432"
  backend:
    build: ../backend
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/saas
    ports:
      - "${BACKEND_PORT}:3000"
    depends_on:
      - database
  frontend:
    build: ../frontend
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - backend
